language: bash
services: docker
before_install:
  - echo "We are in the docker folder"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script: 
    - docker push adrianohenriquess/rest-with-springboot-udemy;
    - docker push adrianohenriquess/mysql-with-springboot-udemy;
  on:
    branch: master
notifications: 
  email: false 